### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 119-120: ordinal not in range(128)

### ISSUE THREAD

**Issue by chipweinberger** [csu/export-saved-reddit#49]
New errors =)

Traceback (most recent call last):
  File "export_saved.py", line 336, in <module>
    main()
  File "export_saved.py", line 330, in main
    save_saved(reddit)
  File "export_saved.py", line 293, in save_saved
    process(reddit, seq, "export-saved", "Reddit - Saved")
  File "export_saved.py", line 275, in process
    write_csv(csv_rows, file_name + ".csv")
  File "export_saved.py", line 261, in write_csv
    if isinstance(r, str) else r for r in row])

**Comment by csu** [comment]
Yea, this has been a pain that I thought we had fixed on Python 2, but for now, if you use Python 3 instead, you shouldn't hit this.

**Comment by MagicFab** [comment]
I get the same with Python 3 (3.7.3rc1) in Debian 10.

**Comment by rachmadaniHaryono** [comment]
can you post the error @MagicFab ?
