### ISSUE TITLE
invalid_grant error processing request

### ISSUE THREAD

**Issue by itripley** [csu/export-saved-reddit#54]
I get this error dunno why

Traceback (most recent call last):
  File "export_saved.py", line 336, in <module>
    main()
  File "export_saved.py", line 330, in main
    save_saved(reddit)
  File "export_saved.py", line 292, in save_saved
    seq = reddit.user.me().saved(limit=None)
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\praw\models\user.py", line 60, in me
    user_data = self._reddit.get(API_PATH['me'])
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\praw\reddit.py", line 320, in get
    data = self.request('GET', path, params=params)
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\praw\reddit.py", line 404, in request
    params=params)
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\prawcore\sessions.py", line 135, in request
    self._authorizer.refresh()
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\prawcore\auth.py", line 328, in refresh
    password=self._password)
  File "C:\Users\afons\AppData\Local\Programs\Python\Python37-32\lib\site-packages\prawcore\auth.py", line 142, in _request_token
    payload.get('error_description'))
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by itripley** [comment]
Wrong passwords oops
